CREATE TABLE zms.dbo.Sanct
(
	S_CODE NCHAR(36) NOT NULL,
	S_SUM DECIMAL(15,2) NOT NULL,
	S_TIP SMALLINT NOT NULL,
	S_OSN INT NOT NULL,
	S_IST SMALLINT NOT NULL,

	S_COM NCHAR(250) NOT NULL,

	Incident_IDCASE BIGINT NOT NULL
);

ALTER TABLE zms.dbo.Sanct ADD CONSTRAINT PK_Sanct PRIMARY KEY (S_CODE);
CREATE UNIQUE INDEX Sanct_idx ON zms.dbo.Sanct (S_CODE ASC);
