CREATE TABLE zms.dbo.Bill
(
   CODE BIGINT NOT NULL,
   CODE_MO NCHAR(6) NOT NULL,
   YEAR INT NOT NULL,
   MONTH SMALLINT NOT NULL,
   NSCHET NCHAR(15) NOT NULL,
   DSCHET DATETIME NOT NULL,
   SUMMAV DECIMAL NOT NULL,
   PLAT NCHAR(5),
   COMENTS NCHAR(250),
   SUMMAP DECIMAL(15,2),
   SANK_MEK DECIMAL(15,2),
   SANK_MEE DECIMAL(15,2),
   SANK_EKMP DECIMAL(15,2)
);

ALTER TABLE zms.dbo.Bill ADD CONSTRAINT PK_Bill PRIMARY KEY (CODE);
CREATE UNIQUE INDEX Bill_idx ON zms.dbo.Bill (CODE ASC
);