CREATE TABLE zms.dbo.Incident
(
	IDCASE BIGINT NOT NULL,
	USL_OK INT NOT NULL,
	VIDPOM INT NOT NULL,
	FOR_POM SMALLINT NOT NULL,
	LPU NCHAR(6) NOT NULL,
	PROFIL INT NOT NULL,
	DEP INT NOT NULL,
	NHISTORY NCHAR(50) NOT NULL,
	DATE_1 DATETIME NOT NULL,
	DATE_2 DATETIME NOT NULL,
	DS1 NCHAR(10) NOT NULL,
	RSLT INT NOT NULL,
	ISHOD INT NOT NULL,
	PRVS INT NOT NULL,
	IDDOKT NCHAR(25) NOT NULL,
	IDSP INT NOT NULL,
	SUMV DECIMAL(15,2) NOT NULL,

	NPR_MO NCHAR(6),
	EXTR INT,
	LPU_1 NCHAR(8),
	PORD BIGINT,
	P_PER SMALLINT,
	DS0 NCHAR(10),
	DS2 NCHAR(100),
	DS3 NCHAR(100),
	VNOV_M INT,
	CODE_MES1 INT,
	CODE_MES2 INT,
	OS_SLUCH INT,
	ED_COL DECIMAL(5,2),
	TARIF DECIMAL(15,2),
	OPLATA SMALLINT,
	SUMP DECIMAL(15,2),
	SANK_IT DECIMAL(15,2),
	COMENTSL NCHAR(250),

	Record_N_ZAP BIGINT NOT NULL
);

ALTER TABLE zms.dbo.Incident ADD CONSTRAINT PK_Incident PRIMARY KEY (IDCASE);
CREATE UNIQUE INDEX Incident_idx ON zms.dbo.Incident (IDCASE ASC);
