CREATE TABLE zms.dbo.Patient
(
	ID_PAC NCHAR(36) NOT NULL,
	VPOLIS SMALLINT NOT NULL,
	NPOLIS NCHAR(20) NOT NULL,
	NOVOR NCHAR(9) NOT NULL,
	SPOLIS NCHAR(10),
	ST_OKATO NCHAR(5),
	SMO NCHAR(5),
	SMO_OGRN NCHAR(15),
	SMO_OK NCHAR(5),
	SMO_NAM NCHAR(100),
	INV SMALLINT,
	VNOV_D INT
);

ALTER TABLE zms.dbo.Patient ADD CONSTRAINT PK_Patient PRIMARY KEY (ID_PAC);
CREATE UNIQUE INDEX Patient_idx ON zms.dbo.Patient (ID_PAC ASC);
