CREATE TABLE zms.dbo.Service
(
	IDSERV NCHAR(36) NOT NULL,
	LPU NCHAR(6) NOT NULL,
	PROFIL INT NOT NULL,
	DET SMALLINT NOT NULL,
	DATE_IN DATETIME NOT NULL,
	DATE_OUT DATETIME NOT NULL,
	DS NCHAR(10) NOT NULL,
	CODE_USL NCHAR(20) NOT NULL,
	KOL_USL DECIMAL(6,2) NOT NULL,
	SUMV_USL DECIMAL(15,2) NOT NULL,
	PRVS INT NOT NULL,
	CODE_MD NCHAR(25) NOT NULL,
	
	LPU_1 NCHAR(8),
	PODR BIGINT,
	VID_VME NCHAR(15),
	TARIF DECIMAL(15,2),
	NPL SMALLINT,
	COMENTU NCHAR(250),

	Incident_IDCASE BIGINT NOT NULL
);

ALTER TABLE zms.dbo.Service ADD CONSTRAINT PK_Service PRIMARY KEY (IDSERV);
CREATE UNIQUE INDEX Service_idx ON zms.dbo.Service (IDSERV ASC);
